<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sophie Cooper">

<title>Changes in Patterns of Geometric Sign Groupings as a Model of Social Dynamics Across Aurignacian Phases</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="endofquarterpaper_files/libs/clipboard/clipboard.min.js"></script>
<script src="endofquarterpaper_files/libs/quarto-html/quarto.js"></script>
<script src="endofquarterpaper_files/libs/quarto-html/popper.min.js"></script>
<script src="endofquarterpaper_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="endofquarterpaper_files/libs/quarto-html/anchor.min.js"></script>
<link href="endofquarterpaper_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="endofquarterpaper_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="endofquarterpaper_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="endofquarterpaper_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="endofquarterpaper_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Changes in Patterns of Geometric Sign Groupings as a Model of Social Dynamics Across Aurignacian Phases</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sophie Cooper </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>The Upper Paleolithic period experienced a rise in more complex social organizations across Europe <span class="citation" data-cites="Boyd_Silk_2020">(<a href="#ref-Boyd_Silk_2020" role="doc-biblioref">Boyd and Silk 2020</a>)</span> coupled with biological evolution. Another distinctive quality of the Upper Paleolithic is the large rise in artwork, both parietal and mobile. Archaeologists have frequently relied upon that artwork as a proxy for cultural difference in order to understand the shifting patterns of social organization and diversity of the Upper Paleolithic <span class="citation" data-cites="baker2024evidence Sauvet_2018 Kuhn_Stiner_2007 Vanhaeren_d">(<a href="#ref-baker2024evidence" role="doc-biblioref">Baker et al. 2024</a>; <a href="#ref-Sauvet_2018" role="doc-biblioref">Sauvet et al. 2018</a>; <a href="#ref-Kuhn_Stiner_2007" role="doc-biblioref">Kuhn and Stiner 2007</a>; <a href="#ref-Vanhaeren_d" role="doc-biblioref">Vanhaeren and d’Errico 2006</a>)</span>. Considered to be the starting point of the Upper Paleolithic, the Aurignacian technocomplex (ca. 43 - 30 k BP) is commonly linked to the dispersal of Homo sapiens across Western Eurasia, and is characterized by lithic and osseus markers <span class="citation" data-cites="Tejero_Grimaldi_2015 Tartar_2012">(<a href="#ref-Tejero_Grimaldi_2015" role="doc-biblioref">Tejero and Grimaldi 2015</a>; <a href="#ref-Tartar_2012" role="doc-biblioref">E. Tartar 2012</a>)</span>, some of which are decorated with geometric signs <span class="citation" data-cites="dutkiewicz2020">(<a href="#ref-dutkiewicz2020" role="doc-biblioref">Dutkiewicz et al. 2020</a>)</span>. In this paper, we investigate the social organization dynamics by analyzing the distribution and variation of geometric sign types found on mobile objects from the Upper Paleolithic in Europe across four phases of the Aurignacian period.</p>
<p>Social organization dynamics of the Upper Paleolithic have previously been explored using statistical analyses of objects to understand patterns of cultural groups. Multivariate analyses of beads from the Gravettian technocomplex suggests an east to west cline of nine cultural groups <span class="citation" data-cites="baker2024evidence">(<a href="#ref-baker2024evidence" role="doc-biblioref">Baker et al. 2024</a>)</span>. Seriation analysis, PCoA, and network analysis were used to identify the groups from 134 discrete bead types recovered from both burial and occupation sites. To validate their claims of cultural groups, <span class="citation" data-cites="baker2024evidence">Baker et al. (<a href="#ref-baker2024evidence" role="doc-biblioref">2024</a>)</span> used a Mantel test to evaluate an isolation-by-distance hypothesis, which proposes that cultural difference can be primarily explained by geographic distance, finding that geographic distance alone did not solely account for the bead distribution. The nine geographically discrete groups encompass the regions of eastern, northwestern and central Europe, the northern and southern Iberian peninsula, southern and northern Italy, and the eastern and western Mediterranean regions.</p>
<p>Similar analyses of personal ornament types from the Aurignacian technocomplex identified fourteen geographically cohesive groups <span class="citation" data-cites="Vanhaeren_d">(<a href="#ref-Vanhaeren_d" role="doc-biblioref">Vanhaeren and d’Errico 2006</a>)</span>. Drawing on ethnographic studies that show how body decoration and ornamentation indicates ethno-linguistic identity, <span class="citation" data-cites="Vanhaeren_d">Vanhaeren and d’Errico (<a href="#ref-Vanhaeren_d" role="doc-biblioref">2006</a>)</span> used Aurignacian personal ornamentation as a proxy for ethno-linguistic diversity. They analyzed 157 distinct ornament types from 98 Aurignacian sites in Europe and the Near East. Geographically cohesive groups sharing similar ornament type associations were identified by seriation, correspondence, and GIS analyses. These groups sweep counter-clockwise throughout western France, northern Spain, the Pyrenees, and the Mediterranean region. <span class="citation" data-cites="Vanhaeren_d">Vanhaeren and d’Errico (<a href="#ref-Vanhaeren_d" role="doc-biblioref">2006</a>)</span> interpret the variation in personal ornament types as evidence of long-lasting cultural differences and as robustly establishing the ethno-linguistic diversity of the Aurignacian.</p>
<p>Cultural difference has also been identified from geometric signs in Upper Paleolithic parietal art from the Cantabrian region of Spain <span class="citation" data-cites="Sauvet_2018">(<a href="#ref-Sauvet_2018" role="doc-biblioref">Sauvet et al. 2018</a>)</span>. Forty-two quadrilateral geometric signs from four cave sites, likely associated with the Magdalenian period, spanning a distance of 30 kilometers were recorded. Multivariate analysis of 45 morphological characteristics of the signs revealed two clusters. To interpret these clusters, <span class="citation" data-cites="Sauvet_2018">Sauvet et al. (<a href="#ref-Sauvet_2018" role="doc-biblioref">2018</a>)</span> draw on case studies of geometric signs as identity markers, including South African engraved ostrich shells from 60 k BP, maker’s marks on Gallo-Roman pottery, and 19th century French craft guild members’ personal marks. Using these case studies as analogies, <span class="citation" data-cites="Sauvet_2018">Sauvet et al. (<a href="#ref-Sauvet_2018" role="doc-biblioref">2018</a>)</span> interpret the Magdalenian geometric signs as identity markers, and the two clusters as representative of cultural groups.</p>
<p>In this study, we extend the use of geometric signs as identity markers to investigate cultural groups in the Aurignacian period. The Aurignacian period spans roughly 43 - 30 k BP, and is largely characterized by material culture indicators, such as carinated scrapers, small-flake tools and split-based bone and ivory tools, as well as an ongoing evolutionary shift from Neanderthals to early modern humans <span class="citation" data-cites="Chu_Richter_2020">(<a href="#ref-Chu_Richter_2020" role="doc-biblioref">Chu and Richter 2020</a>)</span>. The Aurignacian can be divided into phases which are mainly distinguished by shifts in material culture; Proto, Early, Evolved, and Late Aurignacian <span class="citation" data-cites="Tartar_2015">(<a href="#ref-Tartar_2015" role="doc-biblioref">É. Tartar 2015</a>)</span>, as can be seen in <a href="#tbl-aur-table" class="quarto-xref">Table&nbsp;1</a>. <span class="citation" data-cites="Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021">Shao et al. (<a href="#ref-Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021" role="doc-biblioref">2021</a>)</span> divided the Aurignacian into two main phases, Aur-P1 (Proto/Early), which corresponds with the time period of 43–37 k BP, and Aur-P2 (Evolved/Late), which corresponds with the time periods 37-32 k BP. <span class="citation" data-cites="Banks_dErrico_Zilhao_2013">Banks, d’Errico, and Zilhão (<a href="#ref-Banks_dErrico_Zilhao_2013" role="doc-biblioref">2013</a>)</span> used Bayesian modeling methods to further divide Aur-P1 into the Proto and Early Aurignacian, placing the Proto-Aurignacian at 41.5 - 39.9 k BP, and the early Aurignacian at 39.8 - 37.8 k BP. They found that the Proto-Aurignacian occurs during the Greenland Interstadials (GI) 9 and 10, periods of climatic amelioration, while the Early Aurignacian began with the Henrich Stadial, which is characterized by dry and arid conditions, and ends with GI 8.</p>
<div class="cell" data-tbl-cap-location="bottom">
<div id="tbl-aur-table" class="cell quarto-float anchored" data-tbl-cap-location="bottom">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-aur-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 53%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Time Period Name</th>
<th style="text-align: left;">Dates (k cal BP)</th>
<th style="text-align: left;">Material Culture Markers</th>
<th style="text-align: left;">Environmental Context</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Transitional</td>
<td style="text-align: left;">43 - 41.5</td>
<td style="text-align: left;">Sidescrapers, bladelets, split-base points, flake production scheme, Mousterian influences still present</td>
<td style="text-align: left;">Preceeded by Greenland Stadial 12, ends with GI 11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Proto-Aurignacian</td>
<td style="text-align: left;">41.5 - 39.8</td>
<td style="text-align: left;">Large, straight bladelets from prismatic and pyrimidal cores</td>
<td style="text-align: left;">GI 9 and 10</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Early Aurignacian</td>
<td style="text-align: left;">39.8 - 37.8</td>
<td style="text-align: left;">Twisted bladelets produced from carinated cores</td>
<td style="text-align: left;">Begins with Henrich Stadial 4, ends with GI 8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evolved/Late Aurignacian</td>
<td style="text-align: left;">37.8 - 32</td>
<td style="text-align: left;">Backed microblade, more varied tool kits, beginnings of Gravettian influence</td>
<td style="text-align: left;">GI 8 - 6</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-aur-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary of chronological, cultural and environmental characteristics of Aurignacian periods <span class="citation" data-cites="Banks_dErrico_Zilhao_2013 Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021 Chu_Richter_2020 Fletcher_Sánchez">(<a href="#ref-Banks_dErrico_Zilhao_2013" role="doc-biblioref">Banks, d’Errico, and Zilhão 2013</a>; <a href="#ref-Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021" role="doc-biblioref">Shao et al. 2021</a>; <a href="#ref-Chu_Richter_2020" role="doc-biblioref">Chu and Richter 2020</a>; <a href="#ref-Fletcher_Sánchez" role="doc-biblioref">Fletcher et al. 2010</a>)</span>
</figcaption>
</figure>
</div>
</div>
<p>We hypothesize that these phases, and the environmental changes across the Aurignacian, may correspond to changes in social dynamics of cultural groups, as represented by patterns in the distribution of geometric signs. We aim to address the following questions: How do grouping dynamics of geometric signs change across the four phases of the Aurignacian? How do the groupings vary in diversity, size, connectivity, and boundaries? Lastly, what do the patterns tell us about dynamics of social organization throughout the Aurignacian? We answer these questions by first identifying clusters within each phase using seriation and network analyses. We then test the strength of the clusters using modularity and perMANOVA tests. All of our programming in this study was conducted in RStudio.</p>
</section>
<section id="materials-and-methods" class="level1">
<h1>Materials and Methods</h1>
<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Our data comes from SignBase 1.0, an open-access collection of geometric signs on mobile objects from Upper Paleolithic Europe. SignBase 1.0 is a record of objects noting only the presence or absence of each sign on the object, without details of the quantity or sequence of individual signs on a given object. We used the identification of sign types provided by SignBase’s curators <span class="citation" data-cites="dutkiewicz2020">(<a href="#ref-dutkiewicz2020" role="doc-biblioref">Dutkiewicz et al. 2020</a>)</span>. The data set consists of 531 objects found at 65 sites in 13 countries, and records 55 geometric sign types. We excluded signs if they fell under the “other” category, due to the wide range of potential possibilities. We also excluded seven sites from the sample (only one sign present: Willendorf; extreme geographic distance from the other sites: Riparo di Fontana Nuova, Muralovka, Shanidar Cave, and Hayonim Cave; dated much later than the rest of the assemblages: Grotte De La Princesse Pauline and Šandalja II). These exclusions resulted in a sample of 438 objects found at 30 sites in 7 countries, and 54 sign types used in this study (<a href="#fig-site-map" class="quarto-xref">Figure&nbsp;1</a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-site-map" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-site-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="map-and_hist-plot.png" class="img-fluid figure-img" width="1500">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-site-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: A: Map of sites in each Aurignacian phase that contain geometric signs on mobile objects. B: Abundance of signs over time, phases indicated by colours. C. Distribution of object count by site
</figcaption>
</figure>
</div>
</div>
</div>
<p>The distribution of objects across sites is highly skewed, as seen in <a href="#fig-site-map" class="quarto-xref">Figure&nbsp;1</a> C. To minimize the influence of this skewed distribution, we followed <span class="citation" data-cites="Lycett_2019">Lycett (<a href="#ref-Lycett_2019" role="doc-biblioref">2019</a>)</span> in using presence/absence data for each sign at each site, reducing the effect of variation in object count between sites. We used Mantel tests with a Euclidean object abundance distance matrix and a Jaccard distance matrix of sign types. The test seeks to determine the level of correspondence between the matrices through permutational evaluation of the null distribution <span class="citation" data-cites="Mantel_Smouse">(<a href="#ref-Mantel_Smouse" role="doc-biblioref">Smouse and Long 1992</a>)</span>, (here 1000 permutations), producing a Mantel R statistic and a p-value. The R statistic falls between -1, meaning a strong negative correlation, and 1, meaning a strong positive correlation, while a value of 0 means no correlation. The p-value quantifies the probability of obtaining the observed correlation if the null hypothesis were true (we use an alpha value of 0.05 for the threshold of statistical significance). The Mantel tests were performed using the vegan package <span class="citation" data-cites="Vegan2001">(<a href="#ref-Vegan2001" role="doc-biblioref">Oksanen et al. 2001</a>)</span>. The test indicated that there was no significant correlation between object abundance and sign type distribution (R = 0.078, p = 0.092).</p>
<p>Ages of the objects were determined by calibrating the uncalibrated ages provided by SignBase, using the rcarbon package <span class="citation" data-cites="Crema_Bevan_2021">(<a href="#ref-Crema_Bevan_2021" role="doc-biblioref">Crema and Bevan 2021</a>)</span>. The calibrated radiocarbon dates of the sampled data range from approximately 32,893 BP to 44,778 BP, spanning an overall time range of 11,885 years. We assigned each object to a chronological phase following the date ranges recorded in <a href="#tbl-aur-table" class="quarto-xref">Table&nbsp;1</a>. The Transitional phase has 6 sites and 11 sign types, the Proto-Aurignacian has 10 sites and 23 sign types, the Early Aurignacian has 9 sites and 18 sign types, and the Evolved Aurignacian has 9 sites and 19 sign types. A Mantel test to evaluate the correlation between distance in time and distribution of sign types found a statistically significant correlation (R = 0.06, p = 0.01). This confirms that our assumption that a meaningful change in sign types occurs over time during the Aurignacian period.</p>
<p>If the distribution of sign types can be solely explained by geographic distance, then we would see similarity in sign type distribution decreasing as geographic distance increases. This relationship can be investigated using the isolation-by-distance framework, which proposes that cultural difference can be primarily explained by geographic distance <span class="citation" data-cites="Lycett_2019">(<a href="#ref-Lycett_2019" role="doc-biblioref">Lycett 2019</a>)</span>. To confirm that the distribution of sign types is influenced by cultural factors rather than geographic distance, we calculated the correlation between sign type distribution and geography for each phase. We used Mantel tests with a geographic distance matrix and a Jaccard similarity matrix, with the results shown in <a href="#tbl-mantel-table" class="quarto-xref">Table&nbsp;2</a>. None of the phases have a statistically significant correlation between sign type distribution and geographical distance, so the isolation-by-distance hypothesis is rejected.</p>
<div class="cell" data-tbl-cap-location="bottom">
<div id="tbl-mantel-table" class="cell quarto-float anchored" data-tbl-cap-location="bottom">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-mantel-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Aurignacian phase</th>
<th style="text-align: right;">Mantel R</th>
<th style="text-align: right;">Mantel p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Transitional</td>
<td style="text-align: right;">0.421</td>
<td style="text-align: right;">0.081</td>
</tr>
<tr class="even">
<td style="text-align: left;">Proto-Aurignacian</td>
<td style="text-align: right;">-0.188</td>
<td style="text-align: right;">0.872</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Early Aurignacian</td>
<td style="text-align: right;">0.259</td>
<td style="text-align: right;">0.075</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evolved Aurignacian</td>
<td style="text-align: right;">-0.055</td>
<td style="text-align: right;">0.589</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-mantel-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Table of the results per phase for the Mantel test between a Jaccard matrix of sign type diversity and a geographic distance matrix
</figcaption>
</figure>
</div>
</div>
</section>
<section id="cultural-group-detection-using-seriation-and-network-analysis" class="level2">
<h2 class="anchored" data-anchor-id="cultural-group-detection-using-seriation-and-network-analysis">Cultural Group Detection Using Seriation and Network Analysis</h2>
<p>Seriation analysis is the arrangement of data into a linear order to reveal patterns <span class="citation" data-cites="Hahsler_Hornik_Buchta">(<a href="#ref-Hahsler_Hornik_Buchta" role="doc-biblioref">Hahsler, Hornik, and Buchta 2008a</a>)</span>. We used the Brower-Kile <span class="citation" data-cites="Brower_Kile_1988">(<a href="#ref-Brower_Kile_1988" role="doc-biblioref">1988</a>)</span> seriation algorithm from the seriation package <span class="citation" data-cites="seriation_pckge">(<a href="#ref-seriation_pckge" role="doc-biblioref">Hahsler, Hornik, and Buchta 2008b</a>)</span>, in which a unidimensional sequence is generated by reordering the rows and columns to group the presences along the diagonal. To investigate connectivity among clusters of sites in the seriation solution, we used network analysis to represent and quantify the relationship between sites <span class="citation" data-cites="Mills_2017">(<a href="#ref-Mills_2017" role="doc-biblioref">Mills 2017</a>)</span>. Each node is a site, and each edge is a measure of sign type distribution similarity, as computed by the Jaccard similarity algorothm. Results were plotted with the Fruchterman-Reingold layout <span class="citation" data-cites="Fruchterman_Reingold_1991">(<a href="#ref-Fruchterman_Reingold_1991" role="doc-biblioref">Fruchterman and Reingold 1991</a>)</span>, a force-directed graph layout for uniform edge lengths, and network analysis was performed using the vegan <span class="citation" data-cites="Vegan2001">(<a href="#ref-Vegan2001" role="doc-biblioref">Oksanen et al. 2001</a>)</span>, statnet <span class="citation" data-cites="statnet_package">(<a href="#ref-statnet_package" role="doc-biblioref">Pavel N. Krivitsky et al. 2003–2024</a>)</span> and igraph <span class="citation" data-cites="igraph_package">(<a href="#ref-igraph_package" role="doc-biblioref">Csardi and Nepusz 2006</a>)</span> packages.</p>
</section>
<section id="modularity-and-permanova-for-cultural-group-strength" class="level2">
<h2 class="anchored" data-anchor-id="modularity-and-permanova-for-cultural-group-strength">Modularity and PerMANOVA for Cultural Group Strength</h2>
<p>To evaluate the strength of the groupings found in the seriation and network analyses, we used modularity and perMANOVA tests. The modularity test is a community structure network detection method, and quantifies the randomness of the groupings by measuring the fraction of the edges in the network that fall within groups, minus the expected value if the edges were placed at random <span class="citation" data-cites="Newman_2006 Newman_Girvan_2004">(<a href="#ref-Newman_2006" role="doc-biblioref">Newman 2006</a>; <a href="#ref-Newman_Girvan_2004" role="doc-biblioref">Newman and Girvan 2004</a>)</span>. The results are expressed in a score of 0 to 1, with 0 meaning no significant subgroups, and 1 meaning perfect groupings. PerMANOVA quantifies the level of variation between groups versus the level of variation within groups <span class="citation" data-cites="Anderson_2017">(<a href="#ref-Anderson_2017" role="doc-biblioref">Anderson 2017</a>)</span>. The results are expressed by an R<sup>2</sup> statistic, which quantifies how much of the variation in sign distribution can be explained by group membership, a pseudo-F statistic, and a p-value. The pseudo-F statistic compares the total sum of squared dissimilarities between groups to total sum of squared dissimilarities within groups. Larger pseudo-F statistics indicate more separation between groups. The p-value quantifies the probability of obtaining the observed difference if the null hypothesis were true (we use an alpha value of 0.05 for the threshold of statistical significance). The modularity test and perMANOVA were performed using the vegan <span class="citation" data-cites="Vegan2001">(<a href="#ref-Vegan2001" role="doc-biblioref">Oksanen et al. 2001</a>)</span> and igraph <span class="citation" data-cites="igraph_package">(<a href="#ref-igraph_package" role="doc-biblioref">Csardi and Nepusz 2006</a>)</span> packages.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="cultural-group-detection" class="level2">
<h2 class="anchored" data-anchor-id="cultural-group-detection">Cultural Group Detection</h2>
<div class="cell">
<div class="cell-output-display">
<div id="fig-seriation" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-seriation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="endofquarterpaper_files/figure-html/fig-seriation-1.png" class="img-fluid figure-img" width="1248">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-seriation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Seriation analysis of the data, with group membership indicated by color. Restricted group is in yellow, broader group is in blue.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For each of the phases, seriation identifies at least two groups, one with a restricted range of sign types (1-3 types), which tend to be simpler signs, and one with a broader range (up to 14 types), which include more complex signs. Simpler signs composed of fewer components, like line and notch, are the most prevalent across all time periods. Overall, across the four phases, the number of sites in the restricted group tends to be less than or equal to the number of sites in the broader group, with the exception of the final Evolved phase.</p>
<p>In the Transitional phase, there is a relatively small range of sign types compared to other phases. The restricted group consists of Fumane, Pod Hradem, and Geissenklösterle, two of which only have a notch, and one of which has a notch and circumnotch. The broader group consists of Labeko Koba, Hohle Fels, and El Castillo, which vary in their sign composition and have only the line and oblique line (obline) signs in common.</p>
<p>In the Proto-Aurignacian we see an expansion in both the number of sites and range of signs, with no overlap in sites from the Transitional phase, except for Geissenklösterle, which is present in both phases. The restricted group consists of Abri Pataud, Hohlenstein-Stadel, and Mladeč, which only have notches and lines, and Gatzarria which also has a dashline. The broader group consists of Geissenklösterle, Spy, Vogelherd, Grotte du Renne, La Ferrassie, and Les Cottés, where we see a more consistent pattern of a more diverse range of signs, compared to the broader group of the Transitional phase. In addition to line and notch, the obline, radial notch (radnotch), cross, hatching, and circumferential notch (circumnotch) are also frequently found in the broader group.</p>
<p>In the Early Aurignacian, we see appearance of completely new sites with no overlap with the Proto-Aurignacian sites, as well as increased diversity of patterns within the groups. The restricted group consists of Grottes de Fonds-de-Forêt (radnotch and notch), Riparo Bombrini (notch), and Grotte de la Verpillière I (notch and line). The broader group consists of Solutré, Hohle Fels, Castanet, Cellier, Blanchard, and Trou al’Wesse, which contain a wide range of signs in a variety of combinations. In addition to line and notch, the obline, dot and vulva are also frequently found in the broader group.</p>
<p>Lastly, in the Evolved Aurignacian, we see slightly more consistent groups, again with new sites with no overlap with the Early Aurignacian sites, except for Hohle Fels, which also appears in the Transitional phase. Vogelherd also reappears, having appeared earlier in the Proto-Aurignacian.The restricted group consists of Les Rois, Gargas, La Viña, Sirgenstein Cave, and Vindija Cave, with the line, notch, and and obline signs. The broader group consists of Trou Magrite, Bockstein-Törle, Vogelherd, and Hohle Fels. Along with line, notch, and obline, the hatching, and oblique notch (obnotch) signs are also frequently found in the broader group.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-neighbor-net" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-neighbor-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="endofquarterpaper_files/figure-html/fig-neighbor-net-1.png" class="img-fluid figure-img" width="768">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-neighbor-net-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Network analysis of the data
</figcaption>
</figure>
</div>
</div>
</div>
<p>The results of the network analysis supports the restricted-broad groupings identified in <a href="#fig-seriation" class="quarto-xref">Figure&nbsp;2</a>, and provides additional insights into the evolution of connectivity between groups. In the Transitional phase, the network analysis reveals two distinct and disconnected groups. The restricted group consists of Geissenklösterle, Fumane, and Pod Hradem, and the broad group consisting of Hohle Fels, El Castillo, and Labeko Koba, with no connections between the groups. The Proto-Aurignacian phase also shows two clearly defined groups, the broad group consisting of Geissenklösterle, Spy, Vogelherd, and Grotte du Renne, and the restricted group consisting of Mladeč, Hohlenstein-Stadel, Gatzarria, and Abri Pataud. However, it also displays some connectivity between the two groups of sites, with La Ferrassie connected to both groups. Les Cottés stands out with no connections to either group. The Early Aurignacian shows more strongly inter-connected groups – although the shape still suggests two main groups – with Grotte de la Verpillière I in particular having multiple strong connections to both groups. Lastly, the Evolved Aurignacian again shows two main groups, although intra-group connectivity has decreased, with the broad group consisting of Hohle Fels, Trou Magrite, Vogelherd, and Bockstein-Törle, and the restricted group consisting of Gargas, La Viña, Sirgenstein Cave, Vindija Cave, and Les Rois. As for the Early Aurignacian, inter-connectivity between groups continues to be evident in the Evolved Aurignacian, with connections between Trou Magrite, Gargas, and Vindija Cave, and Bockstein-Törle and Gargas, however the strength of inter-connectivity is weaker than in the Early Aurignacian.</p>
<p>In identifying the groups, we referenced both the seriation and network analyses. The results of the above tests allowed us to find two main groups of sites within each phase (<a href="#fig-seriation" class="quarto-xref">Figure&nbsp;2</a>).</p>
</section>
<section id="cultural-group-strength" class="level2">
<h2 class="anchored" data-anchor-id="cultural-group-strength">Cultural Group Strength</h2>
<div class="cell" data-tbl-cap-location="bottom">
<div id="tbl-strength-table" class="cell quarto-float anchored" data-tbl-cap-location="bottom">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-strength-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<colgroup>
<col style="width: 29%">
<col style="width: 16%">
<col style="width: 19%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Aurignacian phase</th>
<th style="text-align: right;">Modularity</th>
<th style="text-align: right;">PerMANOVA R2</th>
<th style="text-align: right;">PerMANOVA F</th>
<th style="text-align: right;">PerMANOVA p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Transitional</td>
<td style="text-align: right;">0.490</td>
<td style="text-align: right;">0.452</td>
<td style="text-align: right;">3.305</td>
<td style="text-align: right;">0.100</td>
</tr>
<tr class="even">
<td style="text-align: left;">Proto-Aurignacian</td>
<td style="text-align: right;">0.496</td>
<td style="text-align: right;">0.274</td>
<td style="text-align: right;">3.021</td>
<td style="text-align: right;">0.012</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Early Aurignacian</td>
<td style="text-align: right;">0.444</td>
<td style="text-align: right;">0.215</td>
<td style="text-align: right;">1.915</td>
<td style="text-align: right;">0.013</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evolved Aurignacian</td>
<td style="text-align: right;">0.480</td>
<td style="text-align: right;">0.224</td>
<td style="text-align: right;">2.020</td>
<td style="text-align: right;">0.022</td>
</tr>
</tbody>
</table>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-strength-table-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Table of the results per phase for the modularity test and perMANOVA
</figcaption>
</figure>
</div>
</div>
<p>The modularity score quantifies the strength of the groupings, showing that the variations in grouping strength between phases are minimal. The Proto-Aurignacian exhibits the strongest groupings, with a score of 0.496, and the Evolved Aurignacian has the weakest groupings, with a score of 0.48. There is a slight increase in modularity between the Transitional period and the Proto-Aurignacian, before an even slighter decrease into the Early Aurignacian, followed by a larger increase with the Evolved Aurignacian.</p>
<p>The perMANOVA R<sup>2</sup> statistic shows the proportion of sign variation that can be explained by group membership. The Transitional period has the highest score of 0.452 while the Early Aurignacian has the lowest score of 0.215. We see a large decline in scores between the Transitional and the Proto-Aurignacian periods, before a slight increase in between the Early and Evolved Aurignacian periods. The pseudo-F statistic quantifies the difference between groups, with the Transitional phase having the highest value of 3.305, and the Early Aurignacian having the lowest value of 1.915. Similar to the R<sup>2</sup> statistic, we see a decline in values between the Transitional and the Proto-Aurignacian periods, before a slight increase in between the Early and Evolved Aurignacian period. The perMANOVA p-value indicates a statistically significant difference in the distribution of signs between the restricted and broad groups for the Proto- , Early, and Evolved Aurignacian phases, but not the Transitional phase (p = 0.1).</p>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>The first aim of our study was to determine how the grouping dynamics of geometric signs changed across four phases of the Aurignacian, specifically in terms of diversity, size, connectivity, and boundaries. The results from <a href="#fig-seriation" class="quarto-xref">Figure&nbsp;2</a> show that each phase can be divided into two main cultural groups, with sign type diversity serving as a major dividing factor, and that group size varied from phase to phase, with a large increase in between the Transitional phase and the Proto-Aurignacian. <a href="#fig-neighbor-net" class="quarto-xref">Figure&nbsp;3</a> shows that group inter-connectivity and intra-connectivity varies from phase to phase, with weak intra-group connections and no inter-group connections in the Transitional phase, to stronger intraconnections and interconnections starting to form in the Proto-Aurignacian, to extremely strong connections (both between and within groups) in the Early Aurignacian, to weaker connections in the Evolved Aurignacian. The modularity tests, as shown in <a href="#tbl-strength-table" class="quarto-xref">Table&nbsp;3</a>, show that the groupings are strongest in the Transitional period and weakest in the Early Aurignacian, and the perMANOVA tests tell us that the Transitional period experiences the highest level of difference between groups, while the Early Aurignacian experiences the least. The Mantel tests, as shown in <a href="#tbl-mantel-table" class="quarto-xref">Table&nbsp;2</a>, tell us that the sign distribution in the Proto-Aurignacian experiences the lowest correlation with geographic distance, while the Early Aurignacian experiences the highest correlation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-group-map" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-group-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="endofquarterpaper_files/figure-html/fig-group-map-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-group-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Map of sites faceted by time period and colored by group number
</figcaption>
</figure>
</div>
</div>
</div>
<p>The geographic boundaries of the groups change from phase to phase (<a href="#fig-group-map" class="quarto-xref">Figure&nbsp;4</a>). In the Transitional phase, sites are widely spread out across Western Europe, and tend to be located closely to the other sites in their groups. The exception is Hohle Fels, which, instead of being located further west with the rest of the sites in the broader group, is located further east, closer to the sites in the restricted group, and almost overlapping with Geissenklösterle. In the Proto-Aurignacian, we see a slightly narrower distribution of sites westward but a spread northward, and more overlapping of sites between groups. In the Early Aurignacian, we see a reduced distribution, with sites clustered closer together. In the Evolved Aurignacian, we see a wider distribution and more distance between sites.</p>
<p>One factor that may influence the geographic structure of sites is the possibility that some sites functioned as aggregation sites. The aggregation/dispersion pattern is defined by <span class="citation" data-cites="conkley_agg">Conkey et al. (<a href="#ref-conkley_agg" role="doc-biblioref">1980</a>)</span> as a type of hunter-gather settlement pattern, in which groups both break off in dispersed fragments and congregate in large groups, typically for various subsistence or social reasons. Aggregation sites are the places where those fragments or individuals congregate, and some archaeological indicators of aggregation sites include proximity to certain environmental resources, as well as a more diverse artifact assemblage <span class="citation" data-cites="conkley_agg">(<a href="#ref-conkley_agg" role="doc-biblioref">Conkey et al. 1980</a>)</span>. Previous studies have also identified evidence of aggregation/dispersion patterns among the early modern humans of the Upper Paleolithic <span class="citation" data-cites="Maher_Conkey_2019 bahn1982inter Bourdier_2013 Svoboda_2013 bahn1982inter white1992rethinking Soffer_Adovasio_Enloe_Audouze_Zubrow_2010 montet-white1994">(<a href="#ref-Maher_Conkey_2019" role="doc-biblioref">Maher and Conkey 2019</a>; <a href="#ref-bahn1982inter" role="doc-biblioref">Bahn 1982</a>, <a href="#ref-bahn1982inter" role="doc-biblioref">1982</a>; <a href="#ref-Bourdier_2013" role="doc-biblioref">Bourdier 2013</a>; <a href="#ref-Svoboda_2013" role="doc-biblioref">Svoboda 2013</a>; <a href="#ref-white1992rethinking" role="doc-biblioref">White 1992</a>; <a href="#ref-Soffer_Adovasio_Enloe_Audouze_Zubrow_2010" role="doc-biblioref">Soffer et al. 2010</a>; <a href="#ref-montet-white1994" role="doc-biblioref">Montet-White 1994</a>)</span>. It is therefore possible that the sites with multiple connections to both groups, such as La Ferrassie in the the Proto-Aurignacian, Grotte de la Verpillière I in the Early Aurignroacian, and Gargas in the Evolved Aurignacian acted as aggregation sites or served a similar purpose. However, without examining environmental data, this remains only a hypothesis at this time.</p>
<p>The second aim of our study was to determine what these patterns tell us about dynamics of social organization throughout the Aurignacian. The results suggest that the Transitional phase was sparsely populated, with minimal interaction between loosely connected groups. For the Proto-Aurignacian, the results suggest a large expansion in social activity, as well as strongly intra-connected groups with some inter-connectivity present, with geographic distance having the least influence on sign distribution. The Early Aurignacian experiences a large surge in inter-connectivity, as well as intra-connectivity strength, with a great deal of connection between groups and an increase in the correlation with geographic distance. The Evolved Aurignacian experiences a decline in connection strength, although it maintains degrees of inter-connectivity.</p>
<p>These results are consistent with existing data on the environmental and population change established during these phases. <span class="citation" data-cites="Shao_Wegener_Klein_Schmidt_Weniger_2024">Shao et al. (<a href="#ref-Shao_Wegener_Klein_Schmidt_Weniger_2024" role="doc-biblioref">2024</a>)</span> tells us that from 45 - 43.25 k BP, the population density in Europe was extremely low, due to the unfavorable environmental conditions of Greenland Stadial 12 (44 k BP) and the slow westward expansion of early modern humans, before being followed by rapid expansion from 43.25 - 41 k BP, with the maximum extent of Proto/Early Aurignacian (Aur-P1) settlement being reached around 41 k BP. This rapid expansion could be what stimulated the emergence of signs as a marker of group membership. Other studies have also found a similar associations in other regions and time period between increases in quantity and diversity of art, and increases in population density <span class="citation" data-cites="smith1992Design hays1993symbol McDonald_Veth_Lilley_2006 Lourandos_1985 barton_clark_cohen1994 mcdonald2012social bernardini2005reconsidering wiessner1984reconsidering smith1992">(<a href="#ref-smith1992Design" role="doc-biblioref">Smith 1992b</a>, <a href="#ref-smith1992" role="doc-biblioref">1992a</a>; <a href="#ref-hays1993symbol" role="doc-biblioref">Hays 1993</a>; <a href="#ref-McDonald_Veth_Lilley_2006" role="doc-biblioref">McDonald, Veth, and Lilley 2006</a>; <a href="#ref-Lourandos_1985" role="doc-biblioref">Lourandos 1985</a>; <a href="#ref-barton_clark_cohen1994" role="doc-biblioref"><strong>barton_clark_cohen1994?</strong></a>; <a href="#ref-mcdonald2012social" role="doc-biblioref">McDonald and Veth 2012</a>; <a href="#ref-bernardini2005reconsidering" role="doc-biblioref">Bernardini 2005</a>; <a href="#ref-wiessner1984reconsidering" role="doc-biblioref">Wiessner 1984</a>)</span>.</p>
<p>Additionally, <span class="citation" data-cites="Banks_dErrico_Zilhao_2013">Banks, d’Errico, and Zilhão (<a href="#ref-Banks_dErrico_Zilhao_2013" role="doc-biblioref">2013</a>)</span> use eco-cultural niche modeling to show that the Heinrich Stadial 4 at the very beginning of the Early Aurignacian resulted in an expansion into new environmental niches, which they hypothesize was associated with expansion of social networks both within and between populations. This likely explains why we see a large increase in both inter-connectivity and intra-connectivity strength in the Early Aurignacian, as well as the increased correlation with geographic distance. Lastly, <span class="citation" data-cites="Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021">Shao et al. (<a href="#ref-Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021" role="doc-biblioref">2021</a>)</span> developed a human-existence probability model for the Aurignacian, finding an expanded, more dispersed settlement area for Evolved/Late Aurignacian (Aur-P2) theorizing that the environmental changes of HS4 lead to humans better adapted to survive in a broader range of climate conditions. <span class="citation" data-cites="Shao_Wegener_Klein_Schmidt_Weniger_2024">Shao et al. (<a href="#ref-Shao_Wegener_Klein_Schmidt_Weniger_2024" role="doc-biblioref">2024</a>)</span> also finds an increase in expansion marking the beginning of the Evolved Aurignacian. Geographic expansion resulting in less group interconnection could explain why we see weaker, more dispersed connections in the Evolved Aurignacian.</p>
<p>This study adds to our knowledge of social networks within the Aurignacian period, as our results suggest dynamic patterns of social exchange and connection. Previous works <span class="citation" data-cites="bahn1982inter Horiuchi_Takakura_2019 Rogers_2013 baker2024evidence Golovanova_Doronichev_Doronicheva_Sapega_Shackley_2021 Gamble_1982">(<a href="#ref-bahn1982inter" role="doc-biblioref">Bahn 1982</a>; <a href="#ref-Horiuchi_Takakura_2019" role="doc-biblioref">Horiuchi and Takakura 2019</a>; <a href="#ref-Rogers_2013" role="doc-biblioref">Rogers 2013</a>; <a href="#ref-baker2024evidence" role="doc-biblioref">Baker et al. 2024</a>; <a href="#ref-Golovanova_Doronichev_Doronicheva_Sapega_Shackley_2021" role="doc-biblioref">Golovanova et al. 2021</a>; <a href="#ref-Gamble_1982" role="doc-biblioref">Gamble 1982</a>)</span> have used material evidence analysis to reconstruct Upper Paleolithic social networks, which research has pointed to as a potential driver of cultural and evolutionary growth <span class="citation" data-cites="Greenbaum_Friesem_Hovers_Feldman_Kolodny_2019 Creanza_Kolodny_Feldman_2017 Cullen_1996">(<a href="#ref-Greenbaum_Friesem_Hovers_Feldman_Kolodny_2019" role="doc-biblioref">Greenbaum et al. 2019</a>; <a href="#ref-Creanza_Kolodny_Feldman_2017" role="doc-biblioref">Creanza, Kolodny, and Feldman 2017</a>; <a href="#ref-Cullen_1996" role="doc-biblioref">Cullen 1996</a>)</span>. <span class="citation" data-cites="Foley_Gamble_2009">Foley and Gamble (<a href="#ref-Foley_Gamble_2009" role="doc-biblioref">2009</a>)</span> places the emergence of complex inter-group connectivity at around 30 k BP, however, our network analysis shows evidence of inter-connectivity beginning at around 41 k BP, perhaps suggesting an earlier emergence of complex inter-connectivity than previously predicted. We hope that dividing the data up into smaller time periods serves to rectify the low temporal resolution that tends to affect network analysis results when analyzing older, more time-averaged data sets <span class="citation" data-cites="Gravel-Miguel_Coward_2023">(<a href="#ref-Gravel-Miguel_Coward_2023" role="doc-biblioref">Gravel-Miguel and Coward 2023</a>)</span>. Additionally, by focusing on change over time, we are able to see social networks as fluid and dynamic, rather than static and bounded <span class="citation" data-cites="Maher_Conkey_2019">(<a href="#ref-Maher_Conkey_2019" role="doc-biblioref">Maher and Conkey 2019</a>)</span>.</p>
<p>One possible limitation is the potential ambiguity that arises with some of the sign types. While <span class="citation" data-cites="Von_Petzinger_2009">Von Petzinger (<a href="#ref-Von_Petzinger_2009" role="doc-biblioref">2009</a>)</span> argues in favor of Aurignacian geometric signs as symbolic expression, potential ambiguity still remains over whether function is consistent across all sign type occurrences, particularly in regards to the simpler sign types composed from fewer elements. We included the more ambiguous sign types because similar sign occurrence may still serve as evidence of cultural connectivity regardless of function, and additionally, greater quantities of included sign types serves to establish stronger connections <span class="citation" data-cites="Gravel-Miguel_Coward_2023">(<a href="#ref-Gravel-Miguel_Coward_2023" role="doc-biblioref">Gravel-Miguel and Coward 2023</a>)</span>. Potential ambiguity may be addressed in the future through the usage of the data recently released in SignBase 2.0 covering sites in Germany, which contains information on the specific order and patterns in which signs occurred.</p>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study both adds to our understanding of Aurignacian social dynamics and suggests potential new directions for future research. The observed social dynamics produced by our methods align with the existing data on the environmental and population conditions of the Upper Paleolithic. We feel that our research opens up new opportunities for the application of these methods to data on artwork variation in other regions and time periods. Our research also suggests an earlier emergence of dynamic inter-connectivity than previously predicted, as we see weaker inter-connections beginning to emerge by 41 k BP, and stronger inter-connections by 38 k BP. Future research directions might involve the analysis of environmental conditions and their interactions with social dynamics, in order to determine whether some of the sites that we have pointed to as potential aggregation sites function as such. Another potential future research direction would be the usage of the more specific data released in SignBase 2.0 in order to counter potential sign type ambiguity.</p>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Anderson_2017" class="csl-entry" role="listitem">
Anderson, Marti J. 2017. <span>“Permutational Multivariate Analysis of Variance (PERMANOVA).”</span> In <em>Wiley StatsRef: Statistics Reference Online</em>, 1–15. John Wiley &amp; Sons, Ltd. <a href="https://doi.org/10.1002/9781118445112.stat07841">https://doi.org/10.1002/9781118445112.stat07841</a>.
</div>
<div id="ref-bahn1982inter" class="csl-entry" role="listitem">
Bahn, Paul G. 1982. <span>“Inter-Site and Inter-Regional Links During the Upper Palaeolithic: The Pyrenean Evidence.”</span> <em>Oxford Journal of Archaeology</em> 1 (3): 247–68.
</div>
<div id="ref-baker2024evidence" class="csl-entry" role="listitem">
Baker, Jack, Solange Rigaud, Daniel Pereira, Lloyd A Courtenay, and Francesco d’Errico. 2024. <span>“Evidence from Personal Ornaments Suggest Nine Distinct Cultural Groups Between 34,000 and 24,000 Years Ago in Europe.”</span> <em>Nature Human Behaviour</em> 8 (3): 431–44.
</div>
<div id="ref-Banks_dErrico_Zilhao_2013" class="csl-entry" role="listitem">
Banks, William E., Francesco d’Errico, and João Zilhão. 2013. <span>“Human–Climate Interaction During the Early Upper Paleolithic: Testing the Hypothesis of an Adaptive Shift Between the Proto-Aurignacian and the Early Aurignacian.”</span> <em>Journal of Human Evolution</em> 64 (1): 39–55. https://doi.org/<a href="https://doi.org/10.1016/j.jhevol.2012.10.001">https://doi.org/10.1016/j.jhevol.2012.10.001</a>.
</div>
<div id="ref-bernardini2005reconsidering" class="csl-entry" role="listitem">
Bernardini, Wesley. 2005. <span>“Reconsidering Spatial and Temporal Aspects of Prehistoric Cultural Identity: A Case Study from the American Southwest.”</span> <em>American Antiquity</em> 70 (1): 31–54.
</div>
<div id="ref-Bourdier_2013" class="csl-entry" role="listitem">
Bourdier, Camille. 2013. <span>“Rock Art and Social Geography in the Upper Paleolithic. Contribution to the Socio-Cultural Function of the Roc-Aux-Sorciers Rock-Shelter (Angles-Sur-l’anglin, France) from the Viewpoint of Its Sculpted Frieze.”</span> <em>Journal of Anthropological Archaeology</em> 32 (4): 368–82. https://doi.org/<a href="https://doi.org/10.1016/j.jaa.2013.05.005">https://doi.org/10.1016/j.jaa.2013.05.005</a>.
</div>
<div id="ref-Boyd_Silk_2020" class="csl-entry" role="listitem">
Boyd, R., and J. B. Silk. 2020. <em>How Humans Evolved</em>. W.W. Norton. <a href="https://books.google.com/books?id=XmrazQEACAAJ">https://books.google.com/books?id=XmrazQEACAAJ</a>.
</div>
<div id="ref-Brower_Kile_1988" class="csl-entry" role="listitem">
Brower, James C., and Kenneth M. Kile. 1988. <span>“Seriation of an Original Data Matrix as Applied to Paleoecology.”</span> <em>Lethaia</em> 21 (1): 79–93. <a href="https://doi.org/10.1111/j.1502-3931.1988.tb01756.x">https://doi.org/10.1111/j.1502-3931.1988.tb01756.x</a>.
</div>
<div id="ref-Chu_Richter_2020" class="csl-entry" role="listitem">
Chu, Wei, and Juergen Richter. 2020. <span>“Aurignacian Cultural Unit.”</span> In <em>Encyclopedia of Global Archaeology</em>, 1–10. Cham: Springer International Publishing. <a href="https://doi.org/10.1007/978-3-319-51726-1_3441-1">https://doi.org/10.1007/978-3-319-51726-1_3441-1</a>.
</div>
<div id="ref-conkley_agg" class="csl-entry" role="listitem">
Conkey, Margaret W., Antonio Beltran, Antonio Beltrán, G. A. Clark, J. Gonzalez Echegaray, J. González Echegaray, M. G. Guenther, et al. 1980. <span>“The Identification of Prehistoric Hunter-Gatherer Aggregation Sites: The Case of Altamira [and Comments and Reply].”</span> <em>Current Anthropology</em> 21 (5): 609–30. <a href="http://www.jstor.org/stable/2741828">http://www.jstor.org/stable/2741828</a>.
</div>
<div id="ref-Creanza_Kolodny_Feldman_2017" class="csl-entry" role="listitem">
Creanza, Nicole, Oren Kolodny, and Marcus W. Feldman. 2017. <span>“Greater Than the Sum of Its Parts? Modelling Population Contact and Interaction of Cultural Repertoires.”</span> <em>Journal of The Royal Society Interface</em> 14 (130): 20170171. <a href="https://doi.org/10.1098/rsif.2017.0171">https://doi.org/10.1098/rsif.2017.0171</a>.
</div>
<div id="ref-Crema_Bevan_2021" class="csl-entry" role="listitem">
Crema, Enrico R, and Andrew Bevan. 2021. <span>“INFERENCE FROM LARGE SETS OF RADIOCARBON DATES: SOFTWARE AND METHODS.”</span> <em>Radiocarbon</em> 63 (1): 23–39. <a href="https://doi.org/10.1017/RDC.2020.95">https://doi.org/10.1017/RDC.2020.95</a>.
</div>
<div id="ref-igraph_package" class="csl-entry" role="listitem">
Csardi, Gabor, and Tamas Nepusz. 2006. <span>“The Igraph Software Package for Complex Network Research.”</span> <em>InterJournal</em>. <a href="https://igraph.org">https://igraph.org</a>.
</div>
<div id="ref-Cullen_1996" class="csl-entry" role="listitem">
Cullen, Ben R. S. 1996. <span>“Cultural Virus Theory and the Eusocial Pottery Assemblage.”</span> In <em>Darwinian Archaeologies</em>, edited by Herbert Donald Graham Maschner, 43–59. Boston, MA: Springer US. <a href="https://doi.org/10.1007/978-1-4757-9945-3_4">https://doi.org/10.1007/978-1-4757-9945-3_4</a>.
</div>
<div id="ref-dutkiewicz2020" class="csl-entry" role="listitem">
Dutkiewicz, Ewa, Gabriele Russo, Saetbyul Lee, and Christian Bentz. 2020. <span>“SignBase, a Collection of Geometric Signs on Mobile Objects in the Paleolithic.”</span> <em>Scientific Data</em> 7 (1): 364. <a href="https://doi.org/10.1038/s41597-020-00704-x">https://doi.org/10.1038/s41597-020-00704-x</a>.
</div>
<div id="ref-Fletcher_Sánchez" class="csl-entry" role="listitem">
Fletcher, William J., Maria Fernanda Sánchez Goñi, Judy R. M. Allen, Rachid Cheddadi, Nathalie Combourieu-Nebout, Brian Huntley, Ian Lawson, et al. 2010. <span>“Millennial-Scale Variability During the Last Glacial in Vegetation Records from Europe.”</span> <em>Quaternary Science Reviews</em>, Vegetation response to millennial-scale variability during the last glacial, 29 (21): 2839–64. <a href="https://doi.org/10.1016/j.quascirev.2009.11.015">https://doi.org/10.1016/j.quascirev.2009.11.015</a>.
</div>
<div id="ref-Foley_Gamble_2009" class="csl-entry" role="listitem">
Foley, Robert, and Clive Gamble. 2009. <span>“The Ecology of Social Transitions in Human Evolution.”</span> <em>Philosophical Transactions of the Royal Society B: Biological Sciences</em> 364 (1533): 3267–79. <a href="https://doi.org/10.1098/rstb.2009.0136">https://doi.org/10.1098/rstb.2009.0136</a>.
</div>
<div id="ref-Fruchterman_Reingold_1991" class="csl-entry" role="listitem">
Fruchterman, Thomas M. J., and Edward M. Reingold. 1991. <span>“Graph Drawing by Force-Directed Placement.”</span> <em>Software: Practice and Experience</em> 21 (11): 1129–64. <a href="https://doi.org/10.1002/spe.4380211102">https://doi.org/10.1002/spe.4380211102</a>.
</div>
<div id="ref-Gamble_1982" class="csl-entry" role="listitem">
Gamble, Clive. 1982. <span>“Interaction and Alliance in Palaeolithic Society.”</span> <em>Man</em> 17 (1): 92–107. <a href="https://doi.org/10.2307/2802103">https://doi.org/10.2307/2802103</a>.
</div>
<div id="ref-Golovanova_Doronichev_Doronicheva_Sapega_Shackley_2021" class="csl-entry" role="listitem">
Golovanova, Liubov V., Vladimir B. Doronichev, Ekaterina V. Doronicheva, Vladimir F. Sapega, and Michael S. Shackley. 2021. <span>“Long-Distance Contacts and Social Networks of the Upper Palaeolithic Humans in the North-Western Caucasus (on Data from Mezmaiskaya Cave, Russia).”</span> <em>Journal of Archaeological Science: Reports</em> 39: 103118. https://doi.org/<a href="https://doi.org/10.1016/j.jasrep.2021.103118">https://doi.org/10.1016/j.jasrep.2021.103118</a>.
</div>
<div id="ref-Gravel-Miguel_Coward_2023" class="csl-entry" role="listitem">
Gravel-Miguel, Claudine, and Fiona Coward. 2023. <span>“Paleolithic Social Networks and Behavioral Modernity.”</span> In <em>The Oxford Handbook of Archaeological Network Research</em>. Oxford University Press. <a href="https://doi.org/10.1093/oxfordhb/9780198854265.013.31">https://doi.org/10.1093/oxfordhb/9780198854265.013.31</a>.
</div>
<div id="ref-Greenbaum_Friesem_Hovers_Feldman_Kolodny_2019" class="csl-entry" role="listitem">
Greenbaum, Gili, David E. Friesem, Erella Hovers, Marcus W. Feldman, and Oren Kolodny. 2019. <span>“Was Inter-Population Connectivity of Neanderthals and Modern Humans the Driver of the Upper Paleolithic Transition Rather Than Its Product?”</span> <em>Quaternary Science Reviews</em> 217: 316–29. https://doi.org/<a href="https://doi.org/10.1016/j.quascirev.2018.12.011">https://doi.org/10.1016/j.quascirev.2018.12.011</a>.
</div>
<div id="ref-Hahsler_Hornik_Buchta" class="csl-entry" role="listitem">
Hahsler, Michael, Kurt Hornik, and Christian Buchta. 2008a. <span>“Getting Things in Order: An Introduction to the r Package Seriation.”</span> <em>Journal of Statistical Software</em> 25 (3): 1–34. <a href="https://doi.org/10.18637/jss.v025.i03">https://doi.org/10.18637/jss.v025.i03</a>.
</div>
<div id="ref-seriation_pckge" class="csl-entry" role="listitem">
———. 2008b. <span>“Getting Things in Order: An Introduction to the r Package Seriation.”</span> <em>Journal of Statistical Software</em> 25 (3): 1–34. <a href="https://doi.org/10.18637/jss.v025.i03">https://doi.org/10.18637/jss.v025.i03</a>.
</div>
<div id="ref-hays1993symbol" class="csl-entry" role="listitem">
Hays, Kelley Ann. 1993. <span>“When Is a Symbol Archaeologically Meaningful? Meaning, Function, and Prehistoric Visual Arts.”</span> <em>Archaeological Theory: Who Sets the Agenda</em>, 81–92.
</div>
<div id="ref-Horiuchi_Takakura_2019" class="csl-entry" role="listitem">
Horiuchi, Shiro, and Jun Takakura. 2019. <span>“Modeling Learning Strategies and the Expansion of the Social Network in the Beginning of Upper Palaeolithic Europe: Analysis by Agent-Based Simulation.”</span> In <em>Learning Among Neanderthals and Palaeolithic Modern Humans: Archaeological Evidence</em>, edited by Yoshihiro Nishiaki and Olaf Jöris, 179–91. Singapore: Springer Nature Singapore. <a href="https://doi.org/10.1007/978-981-13-8980-1_12">https://doi.org/10.1007/978-981-13-8980-1_12</a>.
</div>
<div id="ref-Kuhn_Stiner_2007" class="csl-entry" role="listitem">
Kuhn, Steven L., and Mary C. Stiner. 2007. <span>“Paleolithic Ornaments: Implications for Cognition, Demography and Identity.”</span> <em>Diogenes</em> 54 (2): 40–48. <a href="https://doi.org/10.1177/0392192107076870">https://doi.org/10.1177/0392192107076870</a>.
</div>
<div id="ref-Lourandos_1985" class="csl-entry" role="listitem">
Lourandos, Harry. 1985. <span>“15 - Intensification and Australian Prehistory.”</span> In <em>Prehistoric Hunters-Gatherers</em>, edited by T. Douglas Price and James A. Brown, 385–423. Academic Press. https://doi.org/<a href="https://doi.org/10.1016/B978-0-12-564750-2.50020-2">https://doi.org/10.1016/B978-0-12-564750-2.50020-2</a>.
</div>
<div id="ref-Lycett_2019" class="csl-entry" role="listitem">
Lycett, Stephen J. 2019. <span>“Confirmation of the Role of Geographic Isolation by Distance in Among-Tribe Variations in Beadwork Designs and Manufacture on the High Plains.”</span> <em>Archaeological and Anthropological Sciences</em> 11 (6): 2837–47. <a href="https://doi.org/10.1007/s12520-018-0742-3">https://doi.org/10.1007/s12520-018-0742-3</a>.
</div>
<div id="ref-Maher_Conkey_2019" class="csl-entry" role="listitem">
Maher, Lisa A., and Margaret Conkey. 2019. <span>“Homes for Hunters?: Exploring the Concept of Home at Hunter-Gatherer Sites in Upper Paleolithic Europe and Epipaleolithic Southwest Asia.”</span> <em>Current Anthropology</em> 60 (1): 91–137. <a href="https://doi.org/10.1086/701523">https://doi.org/10.1086/701523</a>.
</div>
<div id="ref-mcdonald2012social" class="csl-entry" role="listitem">
McDonald, Jo, and Peter Veth. 2012. <span>“The Social Dynamics of Aggregation and Dispersal in the Western Desert.”</span> <em>A Companion to Rock Art</em>, 90–102.
</div>
<div id="ref-McDonald_Veth_Lilley_2006" class="csl-entry" role="listitem">
McDonald, Jo, Peter Veth, and Ian Lilley. 2006. <span>“Rock Art and Social Identity: A Comparison of Holocene Graphic Systems in Arid and Fertile Environments.”</span> In <em>Archaeology of Oceania: Australia and the Pacific Islands</em>, 96–115. Malden, Mass: Blackwell Publishing.
</div>
<div id="ref-Mills_2017" class="csl-entry" role="listitem">
Mills, Barbara J. 2017. <span>“Social Network Analysis in Archaeology.”</span> <em>Annual Review of Anthropology</em> 46 (Volume 46, 2017): 379–97. <a href="https://doi.org/10.1146/annurev-anthro-102116-041423">https://doi.org/10.1146/annurev-anthro-102116-041423</a>.
</div>
<div id="ref-montet-white1994" class="csl-entry" role="listitem">
Montet-White, Anta. 1994. <span>“Alternative Interpretations of the Late Upper Paleolithic in Central Europe.”</span> <em>Annual Review of Anthropology</em> 23: 483–508. <a href="http://www.jstor.org/stable/2156023">http://www.jstor.org/stable/2156023</a>.
</div>
<div id="ref-Newman_2006" class="csl-entry" role="listitem">
Newman, M. E. J. 2006. <span>“Modularity and Community Structure in Networks.”</span> <em>Proceedings of the National Academy of Sciences</em> 103 (23): 8577–82. <a href="https://doi.org/10.1073/pnas.0601602103">https://doi.org/10.1073/pnas.0601602103</a>.
</div>
<div id="ref-Newman_Girvan_2004" class="csl-entry" role="listitem">
Newman, M. E. J., and M. Girvan. 2004. <span>“Finding and Evaluating Community Structure in Networks.”</span> <em>Physical Review E</em> 69 (2): 026113. <a href="https://doi.org/10.1103/PhysRevE.69.026113">https://doi.org/10.1103/PhysRevE.69.026113</a>.
</div>
<div id="ref-Vegan2001" class="csl-entry" role="listitem">
Oksanen, Jari, Gavin L. Simpson, F. Guillaume Blanchet, Roeland Kindt, Pierre Legendre, Peter R. Minchin, R. B. O’Hara, et al. 2001. <span>“Vegan: Community Ecology Package.”</span> <a href="https://doi.org/10.32614/CRAN.package.vegan">https://doi.org/10.32614/CRAN.package.vegan</a>.
</div>
<div id="ref-statnet_package" class="csl-entry" role="listitem">
Pavel N. Krivitsky, Mark S. Handcock, David R. Hunter, Carter T. Butts, Michal Bojanowski, Chad Klumb, Steven M. Goodreau, and Martina Morris. 2003–2024. <span>“Statnet: Tools for the Statistical Modeling of Network Data.”</span> Statnet Development Team. <a href="https://statnet.org">https://statnet.org</a>.
</div>
<div id="ref-Rogers_2013" class="csl-entry" role="listitem">
Rogers, Lisa. 2013. <span>“Human-Material Interaction in the Aurignacian of Europe, 35,000-27,000 BP: An Analysis of Marine Shell Ornament Distribution.”</span> PhD thesis, University of Victoria.
</div>
<div id="ref-Sauvet_2018" class="csl-entry" role="listitem">
Sauvet, Georges, Raphaëlle Bourrillon, Diego Garate, Stéphane Petrognani, Olivia Rivero, Eric Robert, and Gilles Tosello. 2018. <span>“The Function of Graphic Signs in Prehistoric Societies: The Case of Cantabrian Quadrilateral Signs.”</span> <em>Quaternary International</em>, SI: Role of art in prehistory-UISPP2014, 491 (October): 99–109. <a href="https://doi.org/10.1016/j.quaint.2017.01.039">https://doi.org/10.1016/j.quaint.2017.01.039</a>.
</div>
<div id="ref-Shao_Limberg_Klein_Wegener_Schmidt_Weniger_Hense_Rostami_2021" class="csl-entry" role="listitem">
Shao, Yaping, Heiko Limberg, Konstantin Klein, Christian Wegener, Isabell Schmidt, Gerd-Christian Weniger, Andreas Hense, and Masoud Rostami. 2021. <span>“Human-Existence Probability of the Aurignacian Techno-Complex Under Extreme Climate Conditions.”</span> <em>Quaternary Science Reviews</em> 263: 106995. https://doi.org/<a href="https://doi.org/10.1016/j.quascirev.2021.106995">https://doi.org/10.1016/j.quascirev.2021.106995</a>.
</div>
<div id="ref-Shao_Wegener_Klein_Schmidt_Weniger_2024" class="csl-entry" role="listitem">
Shao, Yaping, Christian Wegener, Konstantin Klein, Isabell Schmidt, and Gerd-Christian Weniger. 2024. <span>“Reconstruction of Human Dispersal During Aurignacian on Pan-European Scale.”</span> <em>Nature Communications</em> 15 (1): 7406. <a href="https://doi.org/10.1038/s41467-024-51349-y">https://doi.org/10.1038/s41467-024-51349-y</a>.
</div>
<div id="ref-smith1992" class="csl-entry" role="listitem">
Smith, Claire. 1992a. <span>“Colonising with Style: Reviewing the Nexus Between Rock Art, Territorially and the Colonisation and Occupation of Sahul.”</span> <em>Australian Archaeology</em>, no. 34: 34–42. <a href="http://www.jstor.org/stable/40287092">http://www.jstor.org/stable/40287092</a>.
</div>
<div id="ref-smith1992Design" class="csl-entry" role="listitem">
———. 1992b. <span>“Designed Dreaming: Assessing the Relationship Between Style, Social Structure and Environment in Aboriginal Australia.”</span> <em>Australian Archaeology</em>, no. 34: 51–51. <a href="http://www.jstor.org/stable/40287096">http://www.jstor.org/stable/40287096</a>.
</div>
<div id="ref-Mantel_Smouse" class="csl-entry" role="listitem">
Smouse, Peter E., and Jeffrey C. Long. 1992. <span>“Matrix Correlation Analysis in Anthropology and Genetics.”</span> <em>American Journal of Physical Anthropology</em> 35 (S15): 187–213. https://doi.org/<a href="https://doi.org/10.1002/ajpa.1330350608">https://doi.org/10.1002/ajpa.1330350608</a>.
</div>
<div id="ref-Soffer_Adovasio_Enloe_Audouze_Zubrow_2010" class="csl-entry" role="listitem">
Soffer, Olga, James M Adovasio, James G Enloe, Françoise Audouze, and Ezra B. W Zubrow. 2010. <span>“The Roles of Perishable Technologies in Upper Paleolithic Lives.”</span> In <em>The Magdalenian Household</em>, 235–44. SUNY Press.
</div>
<div id="ref-Svoboda_2013" class="csl-entry" role="listitem">
Svoboda, Jiří. 2013. <span>“Art Gravettien de Pavlov i Et VI: Comparaison d’un Site d’agrégation Et d’un Site Épisodique.”</span> <em>Palethnologie. Archéologie Et Sciences Humaines</em>, no. 55 (January). <a href="https://doi.org/10.4000/palethnologie.4945">https://doi.org/10.4000/palethnologie.4945</a>.
</div>
<div id="ref-Tartar_2012" class="csl-entry" role="listitem">
Tartar, Elise. 2012. <span>“The Recognition of a New Type of Bone Tools in Early Aurignacian Assemblages: Implications for Understanding the Appearance of Osseous Technology in Europe.”</span> <em>Journal of Archaeological Science</em> 39 (7): 2348–60. <a href="https://doi.org/10.1016/j.jas.2012.02.003">https://doi.org/10.1016/j.jas.2012.02.003</a>.
</div>
<div id="ref-Tartar_2015" class="csl-entry" role="listitem">
Tartar, Élise. 2015. <span>“Origin and Development of Aurignacian Osseous Technology in Western Europe: A Review of Current Knowledge.”</span> <em>Palethnologie. Archéologie Et Sciences Humaines</em>, no. 77 (December). <a href="https://doi.org/10.4000/palethnologie.706">https://doi.org/10.4000/palethnologie.706</a>.
</div>
<div id="ref-Tejero_Grimaldi_2015" class="csl-entry" role="listitem">
Tejero, José-Miguel, and Stefano Grimaldi. 2015. <span>“Assessing Bone and Antler Exploitation at Riparo Mochi (Balzi Rossi, Italy): Implications for the Characterization of the Aurignacian in South-Western Europe.”</span> <em>Journal of Archaeological Science</em> 61 (September): 59–77. <a href="https://doi.org/10.1016/j.jas.2015.05.003">https://doi.org/10.1016/j.jas.2015.05.003</a>.
</div>
<div id="ref-Vanhaeren_d" class="csl-entry" role="listitem">
Vanhaeren, Marian, and Francesco d’Errico. 2006. <span>“Aurignacian Ethno-Linguistic Geography of Europe Revealed by Personal Ornaments.”</span> <em>Journal of Archaeological Science</em> 33 (8): 1105–28. <a href="https://doi.org/10.1016/j.jas.2005.11.017">https://doi.org/10.1016/j.jas.2005.11.017</a>.
</div>
<div id="ref-Von_Petzinger_2009" class="csl-entry" role="listitem">
Von Petzinger, Genevieve. 2009. <span>“Making the Abstract Concrete: The Place of Geometric Signs in French Upper Paleolithic Parietal Art.”</span> Master of Arts in Anthropology, University of Victoria.
</div>
<div id="ref-white1992rethinking" class="csl-entry" role="listitem">
White, Randall. 1992. <span>“Rethinking the Middle/Upper Paleolithic Transition.”</span> <em>Current Anthropology</em> 33 (S1): 85–108.
</div>
<div id="ref-wiessner1984reconsidering" class="csl-entry" role="listitem">
Wiessner, Polly. 1984. <span>“Reconsidering the Behavioral Basis for Style: A Case Study Among the Kalahari San.”</span> <em>Journal of Anthropological Archaeology</em> 3 (3): 190–234.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>